title: Hello world, it's me, Alicen
description: > # this means to ignore newlines until "baseurl:"
  Creating 2D web-based games in class at St. Paul College. 
permalink: ':title/'
baseurl: "/azschokke.github.io" # the subpath of your site, e.g. /blog
url: "pinehillmedia.net" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Alicen Zschokke # add your name
author-img: headshot-generic.jpg # add your photo
about-author: Student at Saint Paul College on the Computer Programming track, Java emphasis. Eager to learn whatever I can! # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: azschokke # add your Github handle
social-linkedin: Alicen Zschokke # add your Linkedin handle
social-email: alicen.zschokke@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
